user_agent: 'web:scvbotly:v1.0 (by /u/sirkazuo)'
mod_sub: 'SantaClarita'
filtered_subs:
  - conspiracy
  - FauciForPrison
  - ivermectin
  - fauci
  - preppers
  - CCW
  - WhitePeopleTwitter
  - Conservative
  - BlackPeopleTwitter
  - CoronavirusCirclejerk
  - TakeTheJab
  - ChurchOfCOVID
  - JoeRogan